// North American World Schools tournament directory, 2026-27 season.
// Data source: src/data/ws-circuit-2026-27.json, generated by
// scripts/tabroom-ws/scan.py (a full Tabroom calendar sweep + per-tournament
// event scan + the UK TOC bid list). Never hand-edit the JSON; re-run the script.
import data from '@/data/ws-circuit-2026-27.json';

export type TocTier = 'quarters' | 'semis' | 'finals' | '';
export type Mode = 'in-person' | 'online' | 'hybrid';

export interface PostedTournament {
  tourn_id: string;
  name: string;
  startDate: string; // ISO date
  endDate: string; // ISO date (inclusive)
  city: string;
  state: string; // Tabroom state code, or a timezone code for online events
  stateLabel: string; // state code or "Online"
  mode: Mode;
  reg_status: string;
  ws_events: string[];
  toc_tier: TocTier;
  toc_name: string;
  tags: string[];
  url: string;
}

export interface ExpectedTournament {
  tourn_id_prev: string;
  name: string;
  dates_short_prev: string;
  projectedStart: string;
  projectedEnd: string;
  city: string;
  state: string;
  stateLabel: string;
  mode: Mode;
  ws_events_prev: string[];
  toc_tier: TocTier;
  toc_name: string;
  tags: string[];
  url_prev: string;
}

export interface TocBid {
  tier: string;
  dates: string;
  name: string;
  host: string;
  location: string;
}

interface CircuitData {
  generated: string;
  season: string;
  posted: PostedTournament[];
  expected: ExpectedTournament[];
  events_pending: { tourn_id: string; name: string; dates_short: string; city: string; state: string; prev_ws_events: string[]; url: string }[];
  toc_bids: TocBid[];
  toc_unmatched: TocBid[];
}

const circuit = data as unknown as CircuitData;

export const CIRCUIT_GENERATED = circuit.generated;
export const CIRCUIT_SEASON = circuit.season;

/** Every tournament with a World Schools division posted on Tabroom for the
    season, sorted by start date. */
export const postedTournaments: PostedTournament[] = circuit.posted;

/** Hosts that ran a World Schools division last season and have not posted a
    2026-27 edition yet (projected dates = last season's dates plus one year). */
export const expectedTournaments: ExpectedTournament[] = circuit.expected;

export const eventsPending = circuit.events_pending;
export const tocBids: TocBid[] = circuit.toc_bids;

/** TOC bid tournaments that are not on a North American Tabroom page (held
    abroad, or the 2026-27 page has not been created yet). */
export const tocBidsWithoutTabroomPage: TocBid[] = circuit.toc_unmatched;

const TIER_LABEL: Record<string, string> = {
  quarters: 'Quarters bid',
  semis: 'Semis bid',
  finals: 'Finals bid',
};

export function tierLabel(tier: TocTier): string {
  return TIER_LABEL[tier] ?? '';
}

export function modeLabel(mode: Mode): string {
  return mode === 'in-person' ? 'In person' : mode === 'online' ? 'Online' : 'Hybrid';
}

const TAG_LABEL: Record<string, string> = {
  'middle-school': 'Middle school',
  'nsda-springboard-scrimmage': 'NSDA Springboard scrimmage',
  'weeknight-online-series': 'Weeknight online series',
  'novice-only': 'Novice only',
};

export function tagLabels(tags: string[]): string[] {
  return tags.map((t) => TAG_LABEL[t]).filter(Boolean);
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

/** "Sep 11–13, 2026" / "Oct 30–Nov 1, 2026" / "Sep 19, 2026" from ISO bounds. */
export function formatRange(start: string, end: string): string {
  const [y1, m1, d1] = start.split('-').map(Number);
  const [y2, m2, d2] = end.split('-').map(Number);
  const short = (m: number) => MONTHS[m - 1].slice(0, 3);
  if (start === end) return `${short(m1)} ${d1}, ${y1}`;
  if (m1 === m2 && y1 === y2) return `${short(m1)} ${d1}–${d2}, ${y1}`;
  if (y1 === y2) return `${short(m1)} ${d1}–${short(m2)} ${d2}, ${y1}`;
  return `${short(m1)} ${d1}, ${y1}–${short(m2)} ${d2}, ${y2}`;
}

export function monthKey(iso: string): string {
  return iso.slice(0, 7);
}

export function monthLabel(key: string): string {
  const [y, m] = key.split('-').map(Number);
  return `${MONTHS[m - 1]} ${y}`;
}

/** Group by start month, preserving date order. */
export function groupByMonth<T>(items: T[], getDate: (t: T) => string): { key: string; label: string; items: T[] }[] {
  const groups = new Map<string, T[]>();
  for (const it of items) {
    const k = monthKey(getDate(it));
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k)!.push(it);
  }
  return Array.from(groups.entries()).map(([key, its]) => ({ key, label: monthLabel(key), items: its }));
}

/** The "real" competitive calendar: drops middle-school-only meets, the
    weeknight practice series and the free NSDA scrimmages, which get their own
    call-outs on the page. */
export function isCompetitive(t: PostedTournament): boolean {
  return !t.tags.some((x) => x === 'middle-school' || x === 'nsda-springboard-scrimmage' || x === 'weeknight-online-series');
}

export const circuitStats = {
  posted: postedTournaments.length,
  competitive: postedTournaments.filter(isCompetitive).length,
  bidEvents: postedTournaments.filter((t) => t.toc_tier).length,
  online: postedTournaments.filter((t) => t.mode !== 'in-person').length,
  states: new Set(postedTournaments.filter((t) => t.stateLabel !== 'Online').map((t) => t.stateLabel)).size,
  expected: expectedTournaments.length,
  springboard: postedTournaments.filter((t) => t.tags.includes('nsda-springboard-scrimmage')).length,
};
